docs/Komponentengalerie/self-check.md
src/components/documents/SelfCheck/SelfCheckSolution.tsx

This is a follow-up to #11, adding a new `<SelfCheckSolution>`-component. It wraps a `<Solution>` in a `<SelfCheckContent>`, adding the typical "only show during review" behavior by default. Additionally, it provides the `<Solution>` with the `solutionId` from the surrounding context, thus removing the need for duplicating this ID in the Markdown.
The gallery documentation is updated accordingly.

Follow-up: SelfCheckSolution component

---

src/plugins/remark-media/plugin.ts

YouTube videos currently receive a fixed default height. This change allows them to appear in the player's natural 16/9 aspect ratio instead.
This changes the appearance of all elements that currently use the `::youtube` directive (they will use more vertical real estate). If this effect is undesired, we can also default back to the old behavior (fixed default height of `315px`) and introduce a flag such as `{keepAspectRatio}`.

Remark media: allow natural aspect ratio for YouTube videos

---

docs/Komponentengalerie/media-shortcuts.md
src/plugins/remark-media/plugin.ts

Add a new `learningapps` leaf directive to the `remark-media` plugin.
The default height is set to `500px` here because this is what Learningapps suggests in their embed link, and it results in a more sensible aspect ration. However, we can also change this to `315px` as is the case for most other iframes created by this pluign (users can always open the app in full screen).

Add Learningapps media directive

---

src/api/document.ts
src/components/documents/Restricted/index.tsx
src/models/documents/Restricted.ts

- Create and use a custom document model for the `<Restricted>` item, just to keep things clean.
- Don't show the `Hidden` badge to non-admins (the idea of this component is that a non-authorized user simply doesn't see anything).

Cleanup <Restricted>

---

docs/Komponentengalerie/mdx-comments/index.mdx
docusaurus.config.ts
src/components/Figure/styles.module.scss
src/components/documents/MdxComment/Comment/index.tsx

- make the whole figcaption commentable and prevent partial inline-comments
- ensure inlined figcaptions will be outlined when a comment is open
- make `<String />` Components commentable too

polish: make figcaptions commentable

---

src/plugins/remark-comments/plugin.ts
src/plugins/remark-comments/tests/plugin.test.ts

Instead of `commentNr` the attribute `nodeNr` was passed to `<MdxComment />`.

fix wrong name for comment enumeration

---

src/api/document.ts
src/stores/DocumentStore.ts

Each document model must have a initializer in `DocumentStore.ts#CreateDocumentModel`. This was missing for `DocumentType.Restricted`.

fix: register `Restricted` in DocumentTypes and add initializer

---

static/bry-libs/brython_runner.py
static/bry-libs/py_back_trace.py

- line was not provided in case of a syntax_error and the tb crashed. This was fixed by providing explicitely the source python code
- syntax errors had wrong line numbers due to missing application of line_shift
- filename was always "<string>" - provide it explicitely to use the correct name

fix missing code lines and missing error-messages

---

docs/Komponentengalerie/cms-text.mdx
src/components/documents/CmsText/WithCmsText.tsx
src/components/documents/CmsText/index.tsx
src/components/documents/CmsText/shared.ts

In this alternative approach to `<WithCmsText>`, that component takes a dictionary of key to documentRoot IDs, rather than a single ID. It only shows its content, if there is a document available for each entry. Nested `<CmsText>`-elements can refer to the CMS Texts using the keys of that dictionary, rather than having to repeat the UUID.

Rework CMS Text wrapper

---

docs/Komponentengalerie/images.mdx
src/plugins/remark-images/plugin.ts
src/plugins/remark-images/tests/plugin.test.ts

Markdown Content:
```md
```
Invalid HTML (`p` should not be a child of `figcaption`)
```html
<figure>
<figcaption>
<span style={{flexGrow: 1}} />
a [link](https://link.com) caption
<span style={{flexGrow: 1}} />
</figcaption>
</figure>
```
```html
<figure>
<figcaption><span style={{flexGrow: 1}} />a [link](https://link.com) caption<span style={{flexGrow: 1}} /></figcaption>
</figure>
```

fix: prevent adding block content to figcaptions

---

src/plugins/remark-details/plugin.ts
src/plugins/remark-details/tests/plugin.test.ts
src/plugins/remark-link-annotation/tests/plugin.test.ts

add option to support more directive names for details, e.g. that `:::solution` will be transformed to a details component.
Used here 👉 https://github.com/GBSL-Informatik/ict-website

feature: support custom directive names for the remark details plugin

---

src/components/documents/MdxComment/Comment/styles.module.scss
src/components/documents/MdxComment/styles.module.scss

Currently the right border of a commentable element was modified when hovered. This lead to layout shifts.
This fix uses absolutely positioned pseudo-elements to prevent those layout shifts

fix: prevent layout shifts when hovering comments

---

docs/Komponentengalerie/cms-text.mdx
src/components/PermissionsPanel/index.tsx
src/components/documents/CmsText/Code/index.tsx
src/components/documents/CmsText/Code/styles.module.scss
src/components/documents/CmsText/index.tsx
src/components/documents/CmsText/shared.ts

introduce CmsCode and add showPermissionsPanel prop.
Add a new Component `CmsCode` to display code blocks provided by the cms. This can't be achieved directly by writing in the `.mdx`
```md
<CodeBlock language="python">
<CmsText id="some-uuid" />
</CodeBlock>
```
since the CodeBlock Component does not highlight the code, when it is provided as a component instead of a string... Thats why a separate component was needed.
The `CmsText` was still refactored to only return a plain string (and not a span, as before) to make it more generic useable...

refactor: make cms text more generic

---

src/components/documents/CodeEditor/Editor/index.tsx
src/models/documents/Script.ts
src/stores/PageStore.ts

Since turtles are using svg animations, which are identified by an increasing id independent of how many other animated turtle svg's are present, this works only with one active window

only show one running turtle container

---

src/components/PermissionsPanel/AccessBadge/index.tsx
src/components/PermissionsPanel/AccessBadge/styles.module.scss
src/components/PermissionsPanel/UserPermission/AccessPanel.tsx
src/components/PermissionsPanel/UserPermission/index.tsx
src/components/PermissionsPanel/index.tsx
src/components/documents/Restricted/index.tsx
src/components/documents/Solution/index.tsx
src/stores/PermissionStore.ts

- fix: show users permission panel when no permission was present yet
- new: display a access badge indicating the current access level of a user
https://github.com/user-attachments/assets/2052482b-3920-45a0-8edc-501612faf9aa

refactor: show user permission panel even when no permission exists yet

---

src/components/documents/CmsText/CmsImporter/styles.module.scss

`CmsImporter` wrapper now has `max-height: 100vh` and `overflow: scroll`.

Add basic scrolling to Excel import preview.

---

src/components/documents/CodeEditor/index.tsx

in #146 an ugly bug was introduced, that always saved a loaded code-script with the initial value - what resulted in overwriting user code.
However, this should always be prevented and the dynamic behavior should be applicable only when it is a `slim` code block.

critical: fix overwriting code blocks

---

src/components/documents/CodeEditor/utils/bryRunner.ts

I don't yet fully understand the behavior of microtasks with respect to the event loop, but it seems to differ from `setTimeout`. Judging from the comment in `bryRunner.ts#28`, the brython script seems to be unable to access the graphics output with the `scheduleMicrotask` solution.
This PR reverts to the previous `setTimeout` solution.

Revert bryRunner switch from setTimeout to microtask.

---

src/components/PdfViewer/PdfViewer.module.scss

PDF download button was hard to click because it was partially covered. Fixed it by adding a z-index.

Fix partially covered PDF download button.

---

src/components/MdiSelector/index.tsx
src/components/shared/CopyBadge/index.tsx

closes #160
ensure using `color={null}` for icon stacks

fix: color stacked icons

---

src/components/SyncStatus/index.tsx
src/css/custom.scss

Students often misinterpret the green "changes saved checkmark" sync status icon as "my answer is correct". As a result, they don't click the button to have their answer checked and might not realize that they made a mistake.
Suggestion: Change to a different icon, use color-secondary for "syncing" and use "color-primary" for success. Since these are signal colors, they probably shouldn't depend on a custom color scheme (color-primary, color-secondary), so this PR also moves that definition to a set of custom vars in `custom.scss`.
Try it out [here (String answer)](https://deploy-preview-159--teaching-dev.netlify.app/docs/gallery/persistable-documents/answer/string-answers/) or [here (Quill)](https://deploy-preview-159--teaching-dev.netlify.app/docs/gallery/persistable-documents/answer/qui …

Suggestion: Change sync status icon and color scheme.

---

docusaurus.config.ts

Docusaurus can display partials https://docusaurus.io/docs/markdown-features/react#importing-markdown
But partials should not have a frontmatter.
This fix prevents the automatic addition of the page_id to partial pages (startibg with a `_`)

prevent adding page_id to partials

---

docusaurus.config.ts
src/siteConfig/siteConfig.d.ts

Easily extend the pages config, e.g. with custom admonition types:
```ts
pages: {
admonitionTypes: {
keywords: ['aufgabe'],
extendDefaults: true
}
}
```

add options to extend pages configforma

---

src/siteConfig/markdownPluginConfigs.ts

two plugin configs were not used by the recommendations

use default configs for the recommended markdown plugins

---

docusaurus.config.ts

The tagline "Dogfooding Teaching Features" no longer reflects what teaching-dev is about. My suggestion is something simple like "Informatikunterricht heute", but I'm open for different suggestions.

Change tagline.

---

src/components/Admin/ActionRequest/NavSetTargetRequest.tsx
src/components/Navbar/RequestTarget/index.tsx

- Prioritize current class for request target (display on top, primary button).
- Sort the rest alphabetically (display as secondary button).
- Related: Open the dropdown on hover to keep it consistent with the Change User dropdown.

Prioritize current class for request target, sort the rest.

---

src/components/Navbar/AccountSwitcher/index.tsx
src/components/Navbar/AccountSwitcher/styles.module.scss

As a teacher, I want to be able to see which students in my current class are online / offline (especially before using a "Request Target" navigation).
Since the account switcher dropdown is always accessible and it already separates users in the current class from other users, this PR adds a live indicator to each user button in that dropdown.
We could consider only showing that indicator for users in the current class (i.e. the ones displays with a primary button).

Show online status in account switcher

---

docusaurus.config.ts
src/stores/SocketDataStore.ts
src/theme/Root.tsx

Let's try if this fixes the issues with double-connections.
- disable auto-reconnections by socketio
- do reconnections ourselfs and handle connection errors ourselfs (as before, but now it should not be handled twice...)

improve socketio connection stability

---

src/components/Admin/UserTable/User.tsx
src/components/EditingOverview/index.tsx
src/components/EditingOverview/styles.module.scss
src/components/LiveStatusIndicator/index.tsx
src/components/Navbar/AccountSwitcher/index.tsx
src/components/Navbar/LoginProfileButton/index.tsx
src/components/StudentGroup/AddMembersPopup/AddUser.tsx
src/components/StudentGroup/AddMembersPopup/ImportGroup.tsx
src/components/StudentGroup/AddMembersPopup/styles.module.scss
src/components/StudentGroup/index.tsx
src/components/StudentGroup/styles.module.scss

- Factor duplicated live status indicator out into its own component
- To get a better overview of who is currently online during class, add the live status indicator to:
- task state overview
- admin group management panels
- As a result: Rework styling for adding members / gropus to groups

Add more live status indicators

---

src/components/LoggedOutOverlay/index.tsx
src/components/Navbar/AccountSwitcher/index.tsx
src/components/Navbar/LoginProfileButton/index.tsx
src/components/Navbar/PersonalSpaceOverlay/index.tsx
src/components/documents/QuillV2/index.tsx
src/hooks/useDocumentRoot.ts
src/hooks/useDummyId.ts
src/hooks/useFirstMainDocument.ts
src/models/DocumentRoot.ts
src/models/iDocument.ts
src/stores/DocumentRootStore.ts
src/stores/DocumentStore.ts
src/stores/SessionStore.ts
src/theme/Root.tsx

This PR tries to fix the issue with dummy roots present in a connected client, by:
- adding refetch-queue for unfetched document roots (e.g. when trying to create a doc root, but it is already present, then trigger a refetch of it. Stop refetching after 5 tries)
- tracking loadable document roots and show warning, when such a dummy doc that could be loaded, exists longer than 5s (so the document root was obviously not loaded)
- display an overlay, when there are unloaded dummy roots. the check happens every 15s.
additionally
- fix a rehydration error
- add batched docRoots in one action

show sync issues by tracking stalled document roots

---

docusaurus.config.ts
src/siteConfig/siteConfig.d.ts
src/theme/EditThisPage/index.tsx
src/theme/EditThisPage/styles.module.scss

Adds siteConfig options:
```ts
export type ShowEditThisPage = 'always' | 'never' | 'loggedIn' | 'teachers' | 'admins';
export type EditThisPageOption = 'github' | 'github-dev' | 'cms';
/**
* wheter to show the "Edit this page" links on docs and blog pages.
*/
showEditThisPage?: ShowEditThisPage;
/**
* Options for which edit links to show. Only relevant if `showEditThisPage` is not 'never'.
* @default ['github', 'github-dev', 'cms']
* @example To only show the GitHub edit link:
* ```ts
* showEditThisPageOptions: ['github']
* ```
*/
showEditThisPageOptions?: EditThisPageOption[];
/**
* the URL to the CMS to edit the page. Defaults to '/cms/', but can be
* redirected to a different path
* @default '/cms/'
* @example 'https://teaching-dev.gbsl.website/cms/'
*
* OrganizationName and …
```

feature: add edit button options for gh, gh-dev and cms
