- package.json
- src/components/StudentGroup/excelExport.ts
- src/components/StudentGroup/index.tsx
- src/components/StudentGroup/styles.module.scss
- src/components/util/saveAs.ts
- yarn.lock
Implement a basic Excel export for student groups: ID, first name, last name and email per group member.
> Export student groups as Excel file

- src/components/StudentGroup/excelExport.ts
Fix incorrect autoFilter range.
> Fix: Add autoFilter to email column in student group Excel export.

- docs/Komponentengalerie/code-defbox.md
- docs/Komponentengalerie/deflist.mdx
- docs/Komponentengalerie/details.md
- docs/Komponentengalerie/flex-cards.md
- docs/Komponentengalerie/images.mdx
- docs/Komponentengalerie/link-annotation.mdx
- docs/Komponentengalerie/mdx-page.mdx
- docs/Komponentengalerie/media-shortcuts.md
- docs/Komponentengalerie/pdf.mdx
- docs/Komponentengalerie/remark-enumerate-components.mdx
- src/plugins/remark-deflist/plugin.ts
- src/plugins/remark-deflist/tests/plugin.test.ts
use mdxJsxTextElement instead of FlowElement for `dt` and `dd`
> fix: prevent dt and dd to have paragraphs as children

- babel.config.js
- docusaurus.config.ts
- package.json
- yarn.lock
rspack/core@1.1.2 has a reload problem, so pin it's version to 1.1.1 ftm
> chore: update to docusaurus@3.6.2

- .vscode/settings.json
add prettier config and format on save to vsc settings
> chore: add vsc settings file

- src/components/PermissionsPanel/index.tsx
use better defaults for permissions panel position
> polish: permissions panel default position

- src/components/documents/Excalidoc/Editor/index.tsx
- src/components/documents/FileSystem/Directory/NewItem/index.tsx
use default 100% zoom for excalidraw component
> fix: use 100% excalidraw zoom

- package.json
- src/theme/Root.tsx
- yarn.lock
use latest docusaurus-plugin-sass, which resolves all the error messages
> chore: update docusaurus plugin sass

- src/models/documents/Script.ts
- src/stores/DocumentStore.ts
fix merged version history - all loaded versions (of all authors) were shown together. Now the version tree must share the same author
> fix: code history in users view mode

- src/plugins/remark-images/plugin.ts
- src/plugins/remark-images/tests/plugin.test.ts
> fix: bug that lead to remark-images reordering 

- src/components/documents/Restricted/index.tsx
- src/components/documents/Solution/index.tsx
- src/hooks/useDocumentRoot.ts
`<Solutions>` and `<Restricted>`'s are supposed to prevent a common user seeing some content by default. Let's make this the default then...
> refactor: use None-Access for initializing solutions and  restricted's

- src/components/HomepageFeatures/index.tsx
- src/components/Loader/index.tsx
- src/components/documents/CodeEditor/Button/index.tsx
Reverts GBSL-Informatik/teaching-dev#49
> Revert "refactor: fix various rehydration errors"

- src/api/document.ts
- src/hooks/useFirstMainDocument.ts
- src/stores/DocumentRootStore.ts
- src/stores/DocumentStore.ts
Support of https://github.com/GBSL-Informatik/teaching-api/issues/31
> feature: add option for uniqueMain when creating a document

- docs/gallery/tools/qr-codes/generator/index.mdx
- src/components/Cms/Github/Branch/NewBranch/index.tsx
- src/components/Cms/Github/iFile/Dir/index.tsx
- src/components/Cms/Github/iFile/File/FilePreview/AudioPreview/styles.module.scss
- src/components/Cms/Github/iFile/File/FilePreview/ImagePreview/styles.module.scss
- src/components/Cms/Github/iFile/File/FilePreview/PreviewPopup/index.tsx
- src/components/Cms/Github/iFile/File/FilePreview/VideoPreview/styles.module.scss
- src/components/Cms/MdxEditor/GenericAttributeEditor/MyAttributes/index.tsx
- src/components/Cms/MdxEditor/plugins/CatchAllUnknown/GenericJsxDescriptor.tsx
- src/components/Cms/MdxEditor/toolbar/Actions/Save.tsx
- src/components/Cms/MdxEditor/toolbar/Actions/index.tsx
- src/components/Cms/index.tsx
- src/components/shared/FileUpload/index.tsx
- src/components/shared/QR-Code/Generator/QrGrid/index.tsx
- src/components/shared/QR-Code/Generator/QrGrid/styles.module.scss
- src/components/shared/QR-Code/Generator/createDownloadCanvas.ts
- src/components/shared/QR-Code/Generator/index.tsx
- src/components/shared/QR-Code/Generator/styles.module.scss
- src/components/util/apiStateIcon.ts
- src/models/cms/Dir.ts
- src/models/cms/FileStub.ts
- src/models/cms/Github.ts
- src/models/cms/PR.ts
- src/models/cms/iEntry.ts
- src/pages/gh-login.tsx
- src/plugins/remark-images/mdx-editor-plugin/ImageComponent/index.tsx
- src/plugins/remark-images/mdx-editor-plugin/ImageFigureNode.tsx
- src/plugins/remark-images/mdx-editor-plugin/index.ts
- src/plugins/remark-images/mdx-editor-plugin/styles.module.scss
- src/stores/utils/Storage.ts
> refactor: pick changes done during mint week

- docusaurus.config.ts
- src/api/IoEventTypes.ts
- src/components/Admin/ActionRequest/NavReloadRequest.tsx
- src/components/Admin/ActionRequest/NavSetTargetRequest.tsx
- src/components/Admin/NavigationRequest/ReloadRequest.tsx
- src/components/Navbar/AccountSwitcher/index.tsx
- src/components/Navbar/LoginProfileButton/index.tsx
- src/components/Navbar/RequestTarget/index.tsx
- src/components/Navbar/RequestTarget/styles.module.scss
- src/pages/user/index.tsx
- src/pages/user/styles.module.scss
- src/stores/SocketDataStore.ts
- src/theme/NavbarItem/ComponentTypes.tsx
- src/theme/Root.tsx
This PR enables teachers/admins to
- remotely reload all connected clients of a class/room
- to navigate all connected clients of a class/room to the current viewed page...
> feature: reload connected clients remotely

- docs/app-architecture/dokku/index.mdx
- docs/gallery/display/dynamic-values/index.mdx
- docs/gallery/index.mdx
- src/components/DynamicValues/Dyn/index.tsx
- src/components/DynamicValues/Input/index.tsx
- src/components/DynamicValues/Input/styles.module.scss
- src/components/DynamicValues/TemplateCode/index.tsx
- src/components/DynamicValues/Val/index.tsx
- src/components/DynamicValues/index.tsx
- src/components/DynamicValues/templateReplacer.ts
- src/components/StudentGroup/styles.module.scss
- src/components/documents/CodeEditor/SvgEditor/index.tsx
- src/components/documents/CodeEditor/index.tsx
- src/components/shared/SelectInput/styles.module.scss
- src/components/shared/TextAreaInput/styles.module.scss
- src/components/shared/TextInput/styles.module.scss
- src/css/custom.scss
- src/models/Page.ts
- src/models/documents/NetpbmGraphic/index.ts
- src/theme/CodeBlock/extractCodeBlockProps.tsx
Dynamic Template Values which change when the input changes:
This can be achieved through an easy setup:
````md
import { Val, TemplateCode, DynamicInput } from '@tdev-components/DynamicValues';
<DynamicInput name="name" default="Reto" />
<DynamicInput name="zahl" label="Lieblingszahl" default="42" />
Hallo **<Val name="name" />**, deine Lieblingszahl ist <Val name="zahl" as="boxed" />.
<TemplateCode>
```bash
echo "Hallo {{name}}!"
```
</TemplateCode>
In Python würde das wie folgt gemacht: <Val as="code">`print('Hallo {{name}}!')`</Val>.
Verstehst du, weshalb das Ergebnis immer __3__ ergibt?
<TemplateCode>
```py live_py slim
zahl = {{zahl}}
zahl = zahl * 2
zahl = zahl + 9
zahl = zahl - 3
zahl = zahl / 2
zahl = zahl - {{zahl}}
print(zahl)
```
</TemplateCode>
````
> feature: setup dynamic template values

- docusaurus.config.ts
- src/api/base.ts
- src/pages/user/index.tsx
- src/theme/Root.tsx
Some small suggestions for pr #148
> review for #148

- .github/workflows/deploy.yml
- README.md
- docusaurus.config.ts
- siteConfig.ts
- src/pages/gh-login.tsx
- src/siteConfig/siteConfig.d.ts
Minor fix: OAuth client ID was hard-coded.
> Make GH OAuth client ID configurable in siteConfig.

- docs/tdev/gallery/markdown/remark-graphviz/index.mdx
- package.json
- src/plugins/remark-graphviz/plugin.ts
- src/plugins/remark-graphviz/tests/plugin.test.ts
- src/plugins/remark-images/tests/plugin.test.ts
- src/plugins/remark-images/transformer.ts
- src/siteConfig/markdownPluginConfigs.ts
- yarn.lock
Checkout docs here: 👉 https://deploy-preview-174--teaching-dev.netlify.app/docs/gallery/markdown/remark-graphviz/
> add remark graphviz poc

- README.md
- package.json
- updateSync/dependencyCheck.ts
- updateSync/report.ts
- updateSync/tsconfig.json
- updateSync/types.d.ts
- updateSync/updateTdev.ts
- updateSync/util.ts
- updateTdev.config.yaml
- yarn.lock
- Implement a customizable teaching-dev update mechanism including package differ.
- Provide a sane default config file.
- Add documentation.
> Implement teaching-dev update mechanism.

- src/components/util/localFS/requestFileHandle.ts
follow up of #202 to support images from static dir
> img-editor: support images from the static folder

- packages/tdev/excalidoc/ImageMarkupEditor/TopRightUi/index.tsx
- packages/tdev/excalidoc/ImageMarkupEditor/helpers/updateElementsWith.ts
- packages/tdev/excalidoc/ImageMarkupEditor/index.tsx
> excalidraw: add more control over freedraw elements

- src/components/Navbar/LoginProfileButton/AdminNavPopup.tsx
- src/components/Navbar/LoginProfileButton/ProfileButton.tsx
- src/components/Navbar/LoginProfileButton/index.tsx
- src/components/Navbar/LoginProfileButton/styles.module.scss
Adds a hover-dropdown on the profile button when logged in as an admin. This dropdown contains links to the various admin panels.
https://github.com/user-attachments/assets/07bf64f8-d062-4c8b-a9b5-2e90e9224483
> Admin navigation hover-dropdown
